### ISSUE TITLE
ytdl_hook: EDL doesn't support fragmentswithout duration with MP4 DASH

### ISSUE THREAD

**Issue by Xathros1** [flathub/io.mpv.Mpv#159]
Playing youtube videos with mpv results in some video's playing without any sound

```
cb@tumbleweed-pc:~> mpv https://youtu.be/s9TIMDxTpcc
   cplayer: Auto-loading profile 'protocol.https'
 ytdl_hook: EDL doesn't support fragmentswithout duration with MP4 DASH 
     demux: EDL specifies no segments.'
     demux: EDL parsing failed.
     demux: Error in EDL.
     demux: EDL: source file 'edl://!mp4_dash,init=%914%https://rr2---sn-8nxoxu-njol.googlevideo.com/videoplayback?expire=1679177591&ei=F-MVZKfeHannx_AP9NK-oAU&ip=185.231.254.91&id=o-AEp5PMtLTdlITuetFNeHXFkUzvUaOV6WC-QdQrYSM3Do&itag=251&source=youtube&requiressl=yes&mh=0w&mm=31%2C29&mn=sn-8nxoxu-njol%2Csn-4g5lzned&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=1900000&spc=H3gIhg1Ll474K_92gjNfW2Nw3SmjXmQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3654525&dur=235.021&lmt=1665674125804043&mt=1679155505&fvip=3&keepalive=yes&fexp=24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJTVTljvtNPOS-0YRbRD3DxOIXLvL6g__-MzIa-BCmWNAiAbvQF_DlAieleTI-z2IYOuOFf-ruB_Mob3NRWYPQ8ZEQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgLIGF2hcaxwRzYkBXWI4ps3u4Yqq7QfGnRluZVWVmwzECIQC1XVfASLLxx2fUMGMgAE5gLVwBqSH6C_NkzfdvnSx6iQ%3D%3D&range=0-3654525;' has unknown duration.
   cplayer:  (+) Video --vid=1 (*) (vp9 1920x1080 30.000fps)
display-tags: File tags:
display-tags:  Uploader: Uknow
display-tags:  Channel_URL: https://www.youtube.com/channel/UC-EU5_XII6cij1lUbSaPevg
vo/gpu-next/wayland: GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
Cannot load libcuda.so.1
quality_menu: fetching available formats... 
        vd: Using hardware decoding (vaapi).
   cplayer: VO: [gpu-next] 1920x1080 vaapi[nv12]
statusline: V: 00:00:00 / 00:03:54 (0%) Cache: 95s/5MB
auto_profiles: Applying auto profile: full-hd30 
statusline: V: 00:00:03 / 00:03:54 (1%) DS: 4.802/0 Cache: 231s/14MB
   cplayer: 
   cplayer: Exiting... (Quit)
cb@tumbleweed-pc:~> 

```
