### ISSUE TITLE
It is a little difficult to use the flatpak for language learning (needs xclip and libXmu)

### ISSUE THREAD

**Issue by sashinexists** [flathub/io.mpv.Mpv#8]
MPV is popular with the language learning community, I'm currently using it as described by MattVsJapan here: https://www.youtube.com/watch?v=bbg6ztWecbU

Basically it uses an extension for mpv that access xclip to copy subs to the clipboard as they appear. I watch in japanese which I am learning. A texthooker (https://anacreondjt.gitlab.io/docs/texthooker/) is open all the while, which displays whatever is on the clipboard. This means that when I come across a word I am unfamiliar with I can highlight it and create a flashcard with the firefox extensions yomichan easily.

The problem is xclip didn't come with the flatpak package. 

I've now built it, but it was a little difficult and it looks like I can't update it now.

Would it be possible to make this easier, either by including the packages 'xclip' and 'libXmu' or adding them as separate plugins for the flatpak app mpv.

To get my language learning setup I had to add the following to the `io.mpv.Mpv.yml` file.

And then run `flatpak-builder --install builds io.mpv.Mpv.yml`

```
- name: libXmu
      buildsystem: autotools
      sources:
      - type: archive
        url: https://github.com/freedesktop/libXmu/archive/libXmu-1.1.2.tar.gz
        sha256: fb1485a0ffcc360c0cc8fe18f54a2f49af6fc384da743c0b136ab99cc6c6e54c

    - name: xclip
      buildsystem: autotools
      sources:
        - type: archive
          url: https://github.com/astrand/xclip/archive/0.13.tar.gz
          sha256: ca5b8804e3c910a66423a882d79bf3c9450b875ac8528791fb60ec9de667f758
```
(I think mpv is popular with the language learning community so it wouldn't be too esoteric a use case)

Thanks a lot!
